### PR TITLE
This closes #1 by making analysis of word frequency case insensitive

### LINKED ISSUE #1: Analyzing frequency of word occurence does not ignore case
The analysis function does not ignore case, resulting in output that will be an exact copy of the input in the case that it is passed an array similar to:

`['This is a sample', 'THIS IS ALSO A SAMPLE', 'this Is yet ANOTHER sample']`

If `'THIS'` is selected as the starting word, the only possible outcome currently will be the full string of input `'THIS IS ALSO A SAMPLE'`.

The constructor function needs to be refactored to convert all strings to lowercase during analysis, while ideally not storing the converted string. Given the above sample array, this would allow a potential output to be `'THIS Is a SAMPLE'`.

### PR DESCRIPTION
**Pull request by mmlanders23**
Hey @maximumdata, let me know what you think!

### CODE REVIEW

**Comment by mmlanders23** [comment]
Ah I just realized I probably should have added another test condition instead of modifying the first. I can do that this evening (I am in California). @maximumdata

**Comment by maximumdata** [comment]
I pulled your fork and tested it out, and it works great! The only thing I was going to mention was the test case, but you've already pointed it out.

Feel free to devise your own, but I think a test for this case would be to have a new array containing strings that have at least one letter capitalized in every word ( i.e. `['Test seNtence', 'anothEr teSt sentenCe']` ...etc ), send that into the generator, and then the test will pass if the output doesn't equal output.toLowerCase(). Either way, thanks for your contribution (and especially for commenting your addition)! 

Ready to merge once a test is created.

**Comment by mmlanders23** [comment]
Hey @maximumdata. Test added! Let me know what you think.

**Comment by maximumdata** [comment]
@mmlanders23 Thanks a lot for your contribution! My holiday break was a bit longer than most, but I'll be reviewing this PR, and (most likely) merging it later today!

**Comment by maximumdata** [comment]
Merged! Thanks again for contributing!

**Comment by mmlanders23** [comment]
My pleasure!

**Pull request merged**
